animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "The animal at 1 is the 2nd animal and is %s." % animals[1]
print "The 3rd animal is at 2 and is %s." % animals[2]
print "The 1st animal is at 0 and is %s." % animals[0]
print "The animal at 3 is the 4th animal and is %s." % animals[3]
print "The 5th animal is at 4 and is %s." % animals[4]
print "The animal at 2 is the 3rd animal and is %s." % animals[2]
print "The 6th animal is at 5 and is %s." % animals[5]
print "The animal at 4 is the 5th and is %s." % animals[4]